### ISSUE TITLE
Can we have a (pre)release with latest log modifications?

### ISSUE THREAD

**Issue by JacoboSanchez** [PascalMinder/GeoBlock#11]
I was opening an issue for the database cache logs printed always when I observed that latest commit does prevent exactly that. Can we have it in a release version? Is there a way to configure the plugin to work on latest github branch without generating a release?

**Comment by PascalMinder** [comment]
Thanks for opening the issue. I am sorry. I think I forgot to create a new release after the last two commits.

**Comment by PascalMinder** [comment]
I created a new release: https://github.com/PascalMinder/GeoBlock/releases/tag/v0.2.0

**Comment by JacoboSanchez** [comment]
Thank you very much, that would help to have the log cleaner. I tried to make a fork and install as local plugin but did not managed to make Traefik use it

**Comment by PascalMinder** [comment]
A newer version of Traefik allows the use of local plugins. I think, this would allow you to just grab the current code and use it as a local plugin.

**Comment by JacoboSanchez** [comment]
Yes I know, just created the local-plugins folder in the container, posted the code and configured to use it but traefik did not start and did not show anything useful in the logs... will try again at some point when I have time.
FYI: configuration seems to work without updating the it to match the camel case. Thank you again!!
