### ISSUE TITLE
TCP Middleware support or only HTTP?

### ISSUE THREAD

**Issue by zarraozaga** [PascalMinder/geoblock#16]
HI I am trying to use geoblock for tcp requests but It is not working, Can I check if it works with TCP?

**Comment by PascalMinder** [comment]
Currently, the plugin only supports http. I have to look into options how to provide TCP support.

**Comment by zutewas** [comment]
@PascalMinder 
Hi, do you plan to integrate the tcp support in next time? Thx

**Comment by PascalMinder** [comment]
Traefik does currently not allow writing a TCP middleware. (https://github.com/traefik/plugindemo/issues/18#event-7568417538)
