### ISSUE TITLE
How does forceMonthlyUpdate work ?

### ISSUE THREAD

**Issue by lumpidu** [PascalMinder/geoblock#28]
Let's assume I have set `cacheSize: 15000` and  `forceMonthlyUpdate=true`.

Is the monthly update done exactly 1 month after an IP address has been cached or at a fixed interval, e.g. `01.12.2022` ? In the latter case, accessing [GeoJs.io](https://www.geojs.io/) with 15000 entries at once would be like a DoS, right ?

**Comment by PascalMinder** [comment]
If you set the monthly update to true, each IP will be updated 1 month after it was created in the cache.

**Comment by lumpidu** [comment]
Ok, that sounds reasonable. Is there some minimal time between the requests for these updates ?

**Comment by PascalMinder** [comment]
No, since the check will be run on each connection. So, if 10 different IP addresses connect and each of them is in the cache and each of them did not visit since 1 months, each 10 will update around the same time.

**Comment by lumpidu** [comment]
thanks for the clarifications
