### ISSUE TITLE
Log Spamming

### ISSUE THREAD

**Issue by jerrywoo96** [PascalMinder/GeoBlock#32]
Hi,

I'm using portainer, and i also use this middleware with a personal dns server for my own use only so as to restrict public use for dns over https. I'm not sure if this is a reason that cause this log spamming, but i'm pretty sure this can be muted. Or change it to a log that only shows rejected requests which is much more informative. Attached is my screenshot.

![image](https://user-images.githubusercontent.com/26324139/215302327-85b11818-d921-4b17-84c6-8f586f008040.png)

**Comment by PascalMinder** [comment]
It seems to me the middleware restarts always. Try to change the lines `api: "https://get.geojs.io/v1/ip/country/{ip}"` and `unknownCountryApiResponse: "nil"` adding the `"`.

**Comment by PascalMinder** [comment]
It looks like you have at least two different configurations:
![image](https://user-images.githubusercontent.com/1893516/215338152-8e091790-135c-4b46-bdbc-40c7c3d5812b.png)

Did you check all of them?

**Comment by PascalMinder** [comment]
If you use one configuration with multiple containers it will span multiple times thus showing up multiple times in the log. If after starting all the containers you use GeoBlock for, are up and running, the log output should stop.
