### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by roberwinkler** [PascalMinder/geoblock#45]
logLocalRequests
logAllowedRequests
logApiRequests

Where to does geoblock log, Can't find the logentries....

**Comment by PascalMinder** [comment]
They are logged to the default traefik log destination.

**Comment by chemiker** [comment]
I'm posting this in case somebody else ends up here searching for the log file entries:  I was searching in `traefik.log`, `access.log` etc. until I finally realized that the log entries can be found in the log of the docker container.
