### ISSUE TITLE
Getting tls:failed to verify certificate errors in my traefik log

### ISSUE THREAD

**Issue by rama31244** [PascalMinder/geoblock#49]
Hi
I just reinstated the geoblock  plugin after deactivating it for a few months and now all my server sites are blocked and the following error appears in my traefik log
INFO: GeoBlock: 2023/12/24 11:10:37 Get "https://get.geojs.io/v1/ip/country/154.6.***.***": tls: failed to verify certificate: x509: certificate is valid for 4fed2cfbe67222790a2bd3e25350****.2f5f979232bcd6119a206081ceec****traefik.default, not get.geojs.io

Any idea how to fix this? Thanks

**Comment by mixpc** [comment]
In case you had AdGuard(+unbound) installed or acting as Primary DNS, that may be the cause of the issue. For further reference:
https://community.traefik.io/t/how-to-properly-apply-geoblock-plugin-to-traefik-setup/21199

**Comment by rama31244** [comment]
I do indeed have AdGuard and unbound set up so that is almost certainly the issue. Thanks for getting back to me

**Comment by rama31244** [comment]
Yep, whitelisting get.geojs.io fixed the issue. Thanks
