### ISSUE TITLE
Allow request when APIurl timeout

### ISSUE THREAD

**Issue by gsardone** [PascalMinder/geoblock#51]
Hi,

I'm using this plugin and sometimes api calls go in error. It would be great if with a parameter like 'apiContinueOnFailure' we can avoid forbidden error when we got error in api calls.

 
![image](https://github.com/PascalMinder/geoblock/assets/56071044/ebb104a1-6e59-4b2b-adc8-a23c176f4c00)

**Comment by PascalMinder** [comment]
Hi,
I'll look into it. Thanks for the suggestion.

**Comment by PascalMinder** [comment]
Closed by #55
