### ISSUE TITLE
FR: Use Cf-Ipcountry Header

### ISSUE THREAD

**Issue by jerrywoo96** [PascalMinder/geoblock#52]
Hello,

Is it possible to use the `Cf-Ipcountry` header instead of querying the api if the `Cf-Ipcountry` header exists?

Regards,
Jerry

**Comment by PascalMinder** [comment]
Hi @jerrywoo96,
I'll look into it. Thanks for the suggestion.

**Comment by PascalMinder** [comment]
Closed by #55

**Comment by PascalMinder** [comment]
The documentation should be update:
![image](https://github.com/PascalMinder/geoblock/assets/1893516/211f6b28-cdb9-4e66-9388-a4ea8e339794)
