### ISSUE TITLE
Geo js - gives "wrong" ip location

### ISSUE THREAD

**Issue by h1ght** [PascalMinder/geoblock#58]
hello,

ive tested curling this via a server in finnland by hetzner. it gives the "wrong" county code. 
https://www.iplocation.net/ip-lookup
gives different location info. 
i guess this service doenst "filter" hosters correctly?

regards

**Comment by PascalMinder** [comment]
I think it's possible that not all IP addresses will return the correct country code. But there is a setting to change the look-up address for any IP address. If the iplocation.net service works better for you, you can change it in your settings. :)
