### ISSUE TITLE
Traffic blocked woth country code AA when using tailscale VPN

### ISSUE THREAD

**Issue by rama31244** [PascalMinder/geoblock#66]
Hi
I use the latest version of traefik 3 + geoblock plugin and everything was working absolutely fine until recently where for some reason, all my traffic from my own devices is blocked when I have tailscale VPN turned on. I live in australia so just allow traffic with country code AU but when I turn tailscale on, geoblock detects the country code as AA and blocks it. This only started happening recently so I'm not sure if it's something new with geoblock or with tail scale. I could always just allow traffic with country code AA but would prefer to find out why its showing up as AA instead of AU when I have tailscale on

**Comment by boomam** [comment]
To preface, I'm not the maintainer of this plugin, but as a suggestion, you could try adding the [Tailscale CIDR block of 100.64.0.0/10](https://tailscale.com/kb/1015/100.x-addresses) to the `allowedIPAddresses` variable for this plugin.

**Comment by rama31244** [comment]
Ok I'm gonna give it a go and will update here

**Comment by rama31244** [comment]
It's really weird but the problem just went away on its own so might have been an issue with the tailscale servers. Thanks anyway
